version: "3"

services:
  server:
    image: 
    restart: always
    ports:
      - 8000:8000
    command: ["uvicorn", "app.api_server:app", "--host=0.0.0.0"]
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/postgres

  postgres:
    image: postgres:14.2-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres-data:

