openapi: 3.0.3

info:
  title: VictoryVault
  description: Геймификация по венам и стенам
  version: 0.0.1

servers:
  - url: https://server.com


paths:
    /api/achivment:
      $ref: './routes/achivments/achivments.yaml'

    /api/achivment/{id}:
      $ref: './routes/achivments/achivments_detailed.yaml'

    /api/achivment/upload_icon:
      post:
        summary: Позволяет загрузить изображение в систему
        description: Позволяет загрузить изображение ачивки. 
        requestBody:
          required: true
          content:
            image/png:
              schema:
                type: string
                format: binary
        responses:
          '204':
            description: Изображение загружено


components:
  # parameters:
    # $ref: "./parameters/_index.yaml"
  schemas:
    $ref: "./schemas/_index.yaml"
  # responses:
    # $ref: "./responses/_index.yaml"