# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2023-04-08T13:59:17+00:00

from __future__ import annotations

from typing import List, Union

from fastapi import FastAPI, Header
from pydantic import conint

from .models import Acivment, UpdateAchivment

app = FastAPI(
    title='VictoryVault',
    description='Геймификация по венам и стенам',
    version='0.0.1',
    servers=[{'url': 'https://server.com'}],
)


@app.post('/api/achivment', response_model=None, responses={'201': {'model': Acivment}})
def create_achivment(body: Acivment) -> Union[None, Acivment]:
    """
    Создаёт объект ачивки
    """
    pass


@app.get('/api/achivment', response_model=List[Acivment])
def list_achivments(
    page: int,
    size: conint(ge=1, le=200) = 20,
    authorization: str = Header(..., alias='Authorization'),
) -> List[Acivment]:
    pass


@app.post('/api/achivment/upload_icon', response_model=None)
def post_api_achivment_upload_icon() -> None:
    """
    Позволяет загрузить изображение в систему
    """
    pass


@app.get('/api/achivment/{id}', response_model=Acivment)
def get_achivment(id: int) -> Acivment:
    """
    Возвращает ачивку по id
    """
    pass


@app.patch('/api/achivment/{id}', response_model=None)
def update_achivment(body: UpdateAchivment) -> None:
    """
    Обновляет поля ачивки
    """
    pass


@app.delete('/api/achivment/{id}', response_model=None)
def delete_acivment_by_id(id: int) -> None:
    """
    Удаляет ачивку по id
    """
    pass
