# generated by fastapi-codegen:
#   filename:  _build/openapi.yaml
#   timestamp: 2023-04-08T13:59:17+00:00

from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import BaseModel


class AchivmentProperties(BaseModel):
    id: Optional[int] = None
    creator_id: Optional[int] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    title: Optional[str] = None
    description: Optional[str] = None
    text_color: Optional[str] = '#FFFFFF'
    bg_color: Optional[str] = '#000000'


class CreateAchivment(AchivmentProperties):
    icon: bytes


class UpdateAchivment(AchivmentProperties):
    pass


class Acivment(AchivmentProperties):
    icon_link: Optional[str] = None
